---
- hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  pre_tasks:
   - name: Print start message
     shell: echo "I am from vagrant machine"
     
   - name: update apt cache
     apt: update_cache=yes cache_valid_time=3600
          
  roles:
   - { role: "setup-db" }
   
  post_tasks:
   - name: Print finish message
     shell: echo "Setting up env completed"
