---
- hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  pre_tasks:
   - name: update apt cache
     apt: update_cache=yes cache_valid_time=3600
          
  roles:
   - { role: "setup-web-app" }
