---
- hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  pre_tasks:
   - name: Print start message
     shell: echo "I am from vagrant machine"
          
  roles:
   - { role: "setup-haproxy", when: service = "haproxy" }
   - { role: "setup-web-app", when: service = "web-app" }
   - { role: "setup-db", when: service = "db" }
   
  post_tasks:
   - name: Print finish message
     shell: "Setting up env completed"
