---
- name: Installing HAproxy
  apt: name=haproxy state=latest

- name: Setup /etc/default/haproxy file
  template: src=templates/haproxy-default dest=/etc/default/haproxy

- name: Update HAProxy config
  template: src=templates/haproxy_template.cfg dest=/etc/haproxy/haproxy.cfg

- name: start and enable haproxy
  service: name=haproxy state=started enabled=yes
