---
- name: Install Nginx server
  apt: name=nginx state=latest
  
- name: start and enable Nginx server
  service: name=nginx state=started enabled=yes

- name: Remove default Nginx config
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Setup Nginx for routing to application
  template: src=templates/nginxapp.conf dest=/etc/nginx/sites-enabled/app.conf
  
- name: Restart Nginx config
  service: name=nginx state=restarted

- name: Create Dir for SimpleHTTPServer
  file: path={{item}} state=directory
  with_items:
    - /opt/app1
    - /opt/app2

- name: Copy simple index html file to app directory
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: 'templates/app1.html', dest: '/opt/app1/index.html' }
    - { src: 'templates/app2.html', dest: '/opt/app2/index.html' }
    
- name: Start SimpleHTTPServer
  shell: cd {{item.path}}; nohup python -mSimpleHTTPServer {{item.port}} </dev/null >/dev/null 2>&1 &
  with_items:
    - { path: '/opt/app1', port: "8080" }
    - { path: '/opt/app2', port: "8090" }
